### ISSUE TITLE
Token verification failed for email_verified field

### ISSUE THREAD

**Issue by velenyak** [coolishbee/go-verify-apple-id-token#2]
Using the package as suggested in the example
```
        client := apple.New()

	jwtClaims, err := client.VerifyIdToken("clientId", idToken)
	if err != nil {
        fmt.Println(err)
	} else {
		fmt.Println(jwtClaims.Email)
	}
```

The validation always fails with the following error message
```
2024/09/24 10:04:28 1 error(s) decoding:

* 'email_verified' expected type 'string', got unconvertible type 'bool', value: 'true'
```

Example JWT ID token to reproduce the issue: `eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImJkOWVjZDNiODNhOTNkMGNjMTczODBmZGQzZTRiZTVmIn0.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLmV4YW1wbGUuYXBwIiwiZXhwIjoxNzI3MjU1MjIzLCJpYXQiOjE3MjcxNjg4MjMsInN1YiI6InJhbmRvbV9hcHBsZV91c2VyX2lkIiwiY19oYXNoIjoicmFuZG9tX2NfaGFzX3ZhbHVlIiwiZW1haWwiOiJyYW5kb20tdmFsdWVAcHJpdmF0ZXJlbGF5LmFwcGxlaWQuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzX3ByaXZhdGVfZW1haWwiOnRydWUsImF1dGhfdGltZSI6MTcyNzE2ODgyMywibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.VqR1igwpz1uaNQznmjFicjDySSQJD-nj5ToiS1kwSyqtNjDUpgiGW3hvSjjdsQkpcKmKfayNjE-30O_ewB2Nhg`
The claims from this token:
```
{
  "iss": "https://appleid.apple.com",
  "aud": "com.example.app",
  "exp": 1727255223,
  "iat": 1727168823,
  "sub": "random_apple_user_id",
  "c_hash": "random_c_has_value",
  "email": "random-value@privaterelay.appleid.com",
  "email_verified": true,
  "is_private_email": true,
  "auth_time": 1727168823,
  "nonce_supported": true
}
```

Possible solution:
`EmailVerified` should be of type `bool` instead of `string` below
https://github.com/coolishbee/go-verify-apple-id-token/blob/d2c49ac3a1b9a68f98a6cadd17432859372fdc1f/apple/validator.go#L39

Is there a reason that the `EmailVerified` field should be a string?
According to the [specifications](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) it should be a boolean. Anyone else faced a similar issue?

**Comment by coolishbee** [comment]
When I first tested it was a string. 
I updated the package to v0.1.1
Anyway, thanks for reporting the issue.

**Comment by velenyak** [comment]
Thank you for the quick fix @coolishbee 🙏
